import { useEffect, useMemo, useState } from 'react'
import {
  Search,
  Download,
  ChevronLeft,
  ChevronRight,
  Loader2,
  RefreshCw,
  Database,
  Sparkles,
  Gavel,
  ShieldAlert,
} from 'lucide-react'
import { apiFetch, buildApiUrl } from '../lib/api'

const TAB_CONFIG = {
  generated: {
    label: 'Applications',
    icon: Sparkles,
    endpoint: '/api/databases/generated',
    exportEndpoint: '/api/databases/generated/export',
    description: 'Synthetic applications generated by the rules engine and stored in the database.',
    empty: 'No generated applications found for the current search.',
    columns: [
      { key: 'application_id', label: 'Roll No' },
      { key: 'applicant_name', label: 'Name' },
      { key: 'caste_category', label: 'Category' },
      { key: 'family_income', label: 'Income', type: 'currency' },
      { key: 'twelfth_percentage', label: '12th %', type: 'score', suffix: '%' },
      { key: 'mh_cet_percentile', label: 'CET', type: 'score' },
      { key: 'jee_percentile', label: 'JEE', type: 'score' },
      { key: 'predicted_priority_score', label: 'A.I. Score', type: 'scoreBold' },
      { key: 'tier', label: 'Tier', type: 'tier' },
      { key: 'created_at', label: 'Recorded', type: 'date' },
    ],
  },
  decision: {
    label: 'Decision Center Records',
    icon: Gavel,
    endpoint: '/api/databases/decision-center',
    exportEndpoint: '/api/databases/decision-center/export',
    description: 'Applicants individually scored through the Decision Center workflow.',
    empty: 'No Decision Center records found for the current search.',
    columns: [
      { key: 'application_id', label: 'Roll No' },
      { key: 'applicant_name', label: 'Name' },
      { key: 'ml_score', label: 'ML Score', type: 'score' },
      { key: 'final_score', label: 'Final Score', type: 'scoreBold' },
      { key: 'decision_tier', label: 'Decision Tier', type: 'decisionTier' },
      { key: 'is_overridden', label: 'Override', type: 'boolean' },
      { key: 'submitted_by', label: 'User' },
      { key: 'created_at', label: 'Recorded', type: 'date' },
    ],
  },
  overrides: {
    label: 'Override Database',
    icon: ShieldAlert,
    endpoint: '/api/databases/overrides',
    exportEndpoint: '/api/databases/overrides/export',
    description: 'Manual override log with the reason and user responsible for the change.',
    empty: 'No override records found for the current search.',
    columns: [
      { key: 'decision_application_id', label: 'Roll No' },
      { key: 'applicant_name', label: 'Name' },
      { key: 'ml_score', label: 'ML Score', type: 'score' },
      { key: 'override_score', label: 'Override Score', type: 'scoreBold' },
      { key: 'final_tier', label: 'Final Tier', type: 'decisionTier' },
      { key: 'override_reason', label: 'Reason', type: 'multiline' },
      { key: 'override_user', label: 'User' },
      { key: 'created_at', label: 'Recorded', type: 'date' },
    ],
  },
}

function TierBadge({ tier }) {
  const colors = {
    'Tier 1': 'bg-green-500/15 text-green-400 border-green-500/20',
    'Tier 2': 'bg-amber-500/15 text-amber-400 border-amber-500/20',
    'Tier 3': 'bg-red-500/15 text-red-400 border-red-500/20',
    Unscored: 'bg-gray-500/15 text-gray-400 border-gray-500/20',
  }

  return (
    <span className={`px-2 py-0.5 rounded text-xs font-semibold border ${colors[tier] || colors.Unscored}`}>
      {tier}
    </span>
  )
}

function DecisionTierBadge({ tier }) {
  if (!tier) return <TierBadge tier="Unscored" />

  if (tier.includes('Tier 1')) return <TierBadge tier="Tier 1" />
  if (tier.includes('Tier 2')) return <TierBadge tier="Tier 2" />
  if (tier.includes('Tier 3')) return <TierBadge tier="Tier 3" />
  return <TierBadge tier="Unscored" />
}

function formatCurrency(value) {
  if (value == null) return '—'
  return new Intl.NumberFormat('en-IN', {
    style: 'currency',
    currency: 'INR',
    maximumFractionDigits: 0,
  }).format(value)
}

function formatScore(value, suffix = '') {
  if (value == null || value === '') return '—'
  return `${Number(value).toFixed(1)}${suffix}`
}

function formatDate(value) {
  if (!value) return '—'
  const parsed = new Date(`${value}Z`)
  if (Number.isNaN(parsed.getTime())) return value
  return parsed.toLocaleString([], {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  })
}

function renderCell(row, column) {
  const value = row[column.key]

  switch (column.type) {
    case 'currency':
      return <span className="text-sm text-tejas-muted">{formatCurrency(value)}</span>
    case 'score':
      return <span className="text-sm text-tejas-muted">{formatScore(value, column.suffix || '')}</span>
    case 'scoreBold':
      return <span className="text-sm font-bold text-tejas-gold">{formatScore(value, column.suffix || '')}</span>
    case 'tier':
      return <TierBadge tier={value} />
    case 'decisionTier':
      return <DecisionTierBadge tier={value} />
    case 'boolean':
      return (
        <span className={`text-xs font-semibold ${value ? 'text-amber-400' : 'text-tejas-muted-dark'}`}>
          {value ? 'Yes' : 'No'}
        </span>
      )
    case 'date':
      return <span className="text-sm text-tejas-muted">{formatDate(value)}</span>
    case 'multiline':
      return (
        <div className="max-w-[280px] text-sm text-tejas-muted whitespace-normal leading-relaxed">
          {value || '—'}
        </div>
      )
    default:
      return <span className="text-sm font-medium text-tejas-text">{value || '—'}</span>
  }
}

export default function ApplicantDatabase() {
  const [activeTab, setActiveTab] = useState('generated')
  const [searchTerm, setSearchTerm] = useState('')
  const [query, setQuery] = useState('')
  const [page, setPage] = useState(1)
  const [data, setData] = useState({ items: [], total: 0, total_pages: 1, page: 1, page_size: 10 })
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')

  const currentTab = TAB_CONFIG[activeTab]

  useEffect(() => {
    const timeoutId = window.setTimeout(() => {
      setPage(1)
      setQuery(searchTerm.trim())
    }, 300)

    return () => window.clearTimeout(timeoutId)
  }, [searchTerm])

  useEffect(() => {
    async function loadRows() {
      setLoading(true)
      setError('')

      const params = new URLSearchParams({
        page: String(page),
        page_size: '10',
      })

      if (query) params.set('q', query)

      try {
        const res = await apiFetch(`${currentTab.endpoint}?${params.toString()}`)
        if (!res.ok) {
          const err = await res.json().catch(() => ({}))
          throw new Error(err.detail || 'Could not load database records.')
        }

        const payload = await res.json()
        setData(payload)
      } catch (err) {
        setError(err.message)
      } finally {
        setLoading(false)
      }
    }

    loadRows()
  }, [currentTab.endpoint, page, query])

  const exportUrl = useMemo(() => {
    const params = new URLSearchParams()
    if (query) params.set('q', query)
    const suffix = params.toString() ? `?${params.toString()}` : ''
    return buildApiUrl(`${currentTab.exportEndpoint}${suffix}`)
  }, [currentTab.exportEndpoint, query])

  const totalPages = data.total_pages || 1
  const startItem = data.total === 0 ? 0 : (data.page - 1) * data.page_size + 1
  const endItem = data.total === 0 ? 0 : Math.min(data.page * data.page_size, data.total)

  return (
    <div className="p-8 max-w-[1480px] mx-auto h-full flex flex-col">
      <div className="flex items-center justify-between mb-8 animate-fade-in shrink-0 gap-4">
        <div>
          <div className="flex items-center gap-2 mb-2">
            <Database className="w-5 h-5 text-tejas-gold" />
            <h1 className="text-2xl font-bold text-tejas-text tracking-tight">
              Applicant Database
            </h1>
          </div>
          <p className="text-sm text-tejas-muted mt-1">
            Three live database views for generated applications, Decision Center scoring, and override history.
          </p>
        </div>
        <a
          href={exportUrl}
          className="flex items-center gap-2 px-4 py-2 bg-white/5 border border-tejas-border text-tejas-text font-medium text-sm rounded-lg hover:bg-white/10 transition-colors"
        >
          <Download className="w-4 h-4" />
          Export CSV
        </a>
      </div>

      <div className="grid grid-cols-3 gap-3 mb-6 shrink-0">
        {Object.entries(TAB_CONFIG).map(([key, tab]) => {
          const Icon = tab.icon
          const isActive = key === activeTab

          return (
            <button
              key={key}
              onClick={() => {
                setActiveTab(key)
                setSearchTerm('')
                setQuery('')
                setPage(1)
              }}
              className={`rounded-xl border px-4 py-4 text-left transition-all ${isActive
                ? 'border-tejas-gold/40 bg-tejas-gold/10 shadow-[0_0_0_1px_rgba(212,168,67,0.15)]'
                : 'border-tejas-border bg-tejas-card hover:bg-white/[0.02]'
                }`}
            >
              <div className="flex items-center gap-2 mb-2">
                <Icon className={`w-4 h-4 ${isActive ? 'text-tejas-gold' : 'text-tejas-muted'}`} />
                <span className={`text-sm font-semibold ${isActive ? 'text-tejas-text' : 'text-tejas-muted'}`}>
                  {tab.label}
                </span>
              </div>
              <p className="text-xs text-tejas-muted leading-relaxed">
                {tab.description}
              </p>
            </button>
          )
        })}
      </div>

      <div className="flex items-center justify-between mb-6 shrink-0 gap-4">
        <div className="relative">
          <Search className="w-4 h-4 absolute left-3 top-1/2 -translate-y-1/2 text-tejas-muted" />
          <input
            type="text"
            placeholder="Search by roll no or name..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className="bg-tejas-card border border-tejas-border text-sm text-tejas-text rounded-lg pl-9 pr-4 py-2 focus:outline-none focus:border-tejas-gold transition-colors w-80 shadow-sm"
          />
        </div>

        <button
          onClick={() => {
            setSearchTerm('')
            setQuery('')
            setPage(1)
          }}
          className="flex items-center gap-1.5 px-3 py-2 bg-tejas-card border border-tejas-border text-tejas-text hover:text-tejas-gold text-sm rounded-lg transition-colors shadow-sm"
        >
          <RefreshCw className="w-4 h-4" />
          Reset
        </button>
      </div>

      {error && (
        <div className="mb-4 shrink-0 rounded-lg border border-red-500/20 bg-red-500/10 px-4 py-3 text-sm text-red-300">
          {error}
        </div>
      )}

      <div className="bg-tejas-card border border-tejas-border rounded-xl flex-1 flex flex-col overflow-hidden shadow-sm animate-fade-in">
        <div className="px-6 py-4 border-b border-tejas-border/70 shrink-0">
          <h2 className="text-sm font-semibold text-tejas-text">{currentTab.label}</h2>
          <p className="text-xs text-tejas-muted mt-1">{currentTab.description}</p>
        </div>

        <div className="overflow-x-auto flex-1">
          <table className="w-full text-left whitespace-nowrap">
            <thead className="sticky top-0 bg-tejas-card border-b border-tejas-border z-10 shadow-sm">
              <tr>
                {currentTab.columns.map((column) => (
                  <th
                    key={column.key}
                    className="px-6 py-4 text-xs font-semibold text-tejas-muted uppercase tracking-wider"
                  >
                    {column.label}
                  </th>
                ))}
              </tr>
            </thead>
            <tbody className="divide-y divide-tejas-border/50">
              {loading ? (
                <tr>
                  <td colSpan={currentTab.columns.length} className="px-6 py-16 text-center">
                    <div className="flex items-center justify-center gap-3 text-sm text-tejas-muted">
                      <Loader2 className="w-4 h-4 animate-spin" />
                      Loading database records...
                    </div>
                  </td>
                </tr>
              ) : data.items.length > 0 ? (
                data.items.map((row) => (
                  <tr
                    key={row.application_id || row.decision_application_id}
                    className="hover:bg-white/[0.02] transition-colors align-top"
                  >
                    {currentTab.columns.map((column) => (
                      <td key={`${row.application_id || row.decision_application_id}-${column.key}`} className="px-6 py-4">
                        {renderCell(row, column)}
                      </td>
                    ))}
                  </tr>
                ))
              ) : (
                <tr>
                  <td colSpan={currentTab.columns.length} className="px-6 py-12 text-center text-sm text-tejas-muted">
                    {currentTab.empty}
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>

        <div className="bg-tejas-card border-t border-tejas-border p-4 flex items-center justify-between shrink-0">
          <span className="text-sm text-tejas-muted">
            Showing <span className="text-tejas-text font-medium">{startItem}</span> to{' '}
            <span className="text-tejas-text font-medium">{endItem}</span> of{' '}
            <span className="text-tejas-text font-medium">{data.total}</span> entries
          </span>

          <div className="flex items-center gap-2">
            <button
              onClick={() => setPage((current) => Math.max(1, current - 1))}
              disabled={page <= 1 || loading}
              className="p-1 rounded text-tejas-muted hover:text-tejas-text hover:bg-white/5 disabled:opacity-50"
            >
              <ChevronLeft className="w-5 h-5" />
            </button>

            <span className="px-3 py-1 text-sm text-tejas-text bg-tejas-gold/10 rounded-md">
              Page {page} / {totalPages}
            </span>

            <button
              onClick={() => setPage((current) => Math.min(totalPages, current + 1))}
              disabled={page >= totalPages || loading}
              className="p-1 rounded text-tejas-muted hover:text-tejas-text hover:bg-white/5 disabled:opacity-50"
            >
              <ChevronRight className="w-5 h-5" />
            </button>
          </div>
        </div>
      </div>
    </div>
  )
}
